name = "lasoci-web"
main = "./dist/server/entry.mjs"
compatibility_date = "2026-05-21"
compatibility_flags = ["global_fetch_strictly_public"]
no_bundle = true

[vars]
PUBLIC_SUPABASE_URL = "https://pllxyjbknzhgutuhmmuj.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbHh5amJrbnpoZ3V0dWhtbXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNjgwODMsImV4cCI6MjA5NDk0NDA4M30.6_GsRUlmHyWBnjUTF6lNvB3TQePLY1_mzOKFZX5P7Ik"

[[kv_namespaces]]
binding = "SESSION"
id = "755852d44f03430fa95c63703e056aea"

[assets]
directory = "./dist/client"
binding = "ASSETS"
