-- Personas reales que faltaban (la lectura anterior via Drive se truncaba)
insert into socios (apellidos, nombre, email, telefono, idioma, rol, activo) values
  ('AMUTIO PERAITA', 'M. ANGELES', 'm..angeles.amutio.peraita.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 1', '', 'x.numero.1.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 4', '', 'x.numero.4.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('GUERRA COLSA', 'INMACULADA', 'inmaculada.guerra.colsa.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('TORO ALBA', 'FRANCISCO JAVIER', 'francisco.javier.toro.alba.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('GESTOSO CARIDE', 'GONZALO', 'gonzalo.gestoso.caride.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('LOPEZ DEL AMO', 'ESPERANZA', 'esperanza.lopez.del.amo.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('PALOMARES ALONSO', 'PABLO', 'pablo.palomares.alonso.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('DE GREGORIO MUÑOZ', 'FRANCISCO JAVIER', 'francisco.javier.de.gregorio.munoz.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('SAINZ DE LA MAZA', 'JUAN CARLOS', 'juan.carlos.sainz.de.la.maza.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 6', '', 'x.numero.6.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('LOPEZ-CORTIJO LOPEZ', 'JUAN', 'juan.lopezcortijo.lopez.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('FAJIN OCERIN', 'ANTONIO ROQUE', 'antonio.roque.fajin.ocerin.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('CASADO FUENTES', 'EDUARDO', 'eduardo.casado.fuentes.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('', 'KOTTE', 'kotte.x.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 2', '', 'x.numero.2.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('HURTADO DE MENDOZA VELASCO', 'JOSE', 'jose.hurtado.de.mendoza.velasco.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('ULLOA SALDAÑA', 'OSCAR', 'oscar.ulloa.saldana.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('HERNANDEZ JIMENEZ', 'PABLO', 'pablo.hernandez.jimenez.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 5', '', 'x.numero.5.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('CASAS POY', 'JAIME', 'jaime.casas.poy.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('PENDIENTE DE JAIME', '', 'x.pendiente.de.jaime.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('IGLESIAS BALAGUER', 'JUAN JOSE', 'juan.jose.iglesias.balaguer.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('ARCE MURILLO', 'PABLO', 'pablo.arce.murillo.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('RODRIGUEZ CHAMORRO', 'LUIS MIGUEL', 'luis.miguel.rodriguez.chamorro.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('LARGO FERNANDEZ', 'FERNANDO', 'fernando.largo.fernandez.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('NAVARRO ALVAREZ DE QUEVEDO', 'CRISTINA', 'cristina.navarro.alvarez.de.quevedo.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('COLORADO MORENO', 'ALFONSO', 'alfonso.colorado.moreno.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('DE LA RED SANCHEZ', 'JUAN CARLOS', 'juan.carlos.de.la.red.sanchez.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('JURADO NEVA', 'MARIA JOSE', 'maria.jose.jurado.neva.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true)
on conflict (email) do nothing;

insert into candidaturas (socio_id, territorio_id, estado, tipo_asociado, seccion, interes_rector, candidatura_presentada) values
  ((select id from socios where email='m..angeles.amutio.peraita.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='LOGROÑO'), 'ACTIVO', 'DELEGADO', 'PADEL LOGROÑO', true, true),
  ((select id from socios where email='x.numero.1.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='LA SELVA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='x.numero.4.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='LLUÇANÈS'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='inmaculada.guerra.colsa.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID'), 'ACTIVO', 'DELEGADO', 'PADEL MADRID', true, true),
  ((select id from socios where email='francisco.javier.toro.alba.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'ACTIVO', 'DELEGADO', 'ACTIVIDADES SUBACUATICAS MADRID', true, true),
  ((select id from socios where email='gonzalo.gestoso.caride.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='esperanza.lopez.del.amo.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID'), 'ACTIVO', 'DELEGADO', 'ESQUI MADRID', true, true),
  ((select id from socios where email='pablo.palomares.alonso.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='francisco.javier.de.gregorio.munoz.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='juan.carlos.sainz.de.la.maza.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='x.numero.6.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MOIANÈS'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='juan.lopezcortijo.lopez.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MURCIA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='antonio.roque.fajin.ocerin.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MURCIA'), 'ACTIVO', 'DELEGADO', 'KARTING MURCIA', true, true),
  ((select id from socios where email='eduardo.casado.fuentes.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='NAVARRA'), 'ACTIVO', 'DELEGADO', 'MULTIAVENTURA NAVARRA', true, true),
  ((select id from socios where email='kotte.x.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='NAVARRA'), 'ACTIVO', 'SOCIO', null, true, false),
  ((select id from socios where email='x.numero.2.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='OSONA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='jose.hurtado.de.mendoza.velasco.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='PAIS VASCO'), 'ACTIVO', 'DELEGADO', 'GASTRONOMIA BILBAO', true, true),
  ((select id from socios where email='oscar.ulloa.saldana.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='PAIS VASCO'), 'ACTIVO', 'DELEGADO', 'GOLF BIZKAIA', true, true),
  ((select id from socios where email='pablo.hernandez.jimenez.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='SANTA CRUZ DE TENERIFE'), 'ACTIVO', 'DELEGADO', 'VELA Y MOTONAUTICA TENERIFE', true, true),
  ((select id from socios where email='x.numero.5.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='TERRA ALTA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='jaime.casas.poy.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='VALENCIA (CIUTAT)'), 'ACTIVO', 'DELEGADO', 'MUSICA MODERNA VALENCIA', true, true),
  ((select id from socios where email='x.pendiente.de.jaime.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='VALENCIA (CIUTAT)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='juan.jose.iglesias.balaguer.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='ANDALUCIA (HUE,COR,CAD,SEV)'), 'ACTIVO', 'DELEGADO', 'GASTRONOMIA SEVILLA', true, true),
  ((select id from socios where email='pablo.arce.murillo.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='CASTILLA Y LEON'), 'ACTIVO', 'DELEGADO', 'F.S. LEON', true, true),
  ((select id from socios where email='luis.miguel.rodriguez.chamorro.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='CASTILLA-LA MANCHA'), 'ACTIVO', 'DELEGADO', 'BICI T.T. CIUDAD REAL', true, true),
  ((select id from socios where email='fernando.largo.fernandez.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='CASTILLA Y LEON'), 'ACTIVO', 'DELEGADO', 'MOTOTURISMO CASTILLA Y LEON', true, true),
  ((select id from socios where email='cristina.navarro.alvarez.de.quevedo.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='alfonso.colorado.moreno.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='juan.carlos.de.la.red.sanchez.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='maria.jose.jurado.neva.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='ANDALUCIA (HUE,COR,CAD,SEV)'), 'ACTIVO', 'DELEGADO', 'MULTIAVENTURA CADIZ', true, true);
