-- ============================================================
-- Migracion de datos reales RECTORES (Google Sheets -> Supabase)
-- ============================================================

insert into ccaa (codigo, nombre, es_afin) values
  ('ANDALUCIA', 'Andalucia', true),
  ('ARAGON', 'Aragon', true),
  ('ASTURIAS', 'Asturias', true),
  ('CANTABRIA', 'Cantabria', true),
  ('CASTILLA Y LEON', 'Castilla Y Leon', true),
  ('CASTILLA-LA MANCHA', 'Castilla-La Mancha', true),
  ('CATALUÑA', 'Cataluña', false),
  ('COMUNIDAD VALENCIANA', 'Comunidad Valenciana', false),
  ('EXTREMADURA', 'Extremadura', true),
  ('GALICIA', 'Galicia', true),
  ('ISLAS BALEARES', 'Islas Baleares', false),
  ('ISLAS CANARIAS', 'Islas Canarias', true),
  ('LA RIOJA', 'La Rioja', true),
  ('MADRID', 'Madrid', true),
  ('MURCIA', 'Murcia', true),
  ('NAVARRA', 'Navarra', true),
  ('PAIS VASCO', 'Pais Vasco', true)
on conflict (codigo) do nothing;

insert into territorios (ccaa_id, nombre, cuota_total) values
  ((select id from ccaa where codigo='CATALUÑA'), 'ALT CAMP', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'ALT EMPORDA', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'ALT PENEDES', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'ALT URGELL', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'ALTA RIBAGORÇA', 1),
  ((select id from ccaa where codigo='ANDALUCIA'), 'ANDALUCIA (ALM,GRA,JAE,MAL)', 5),
  ((select id from ccaa where codigo='ANDALUCIA'), 'ANDALUCIA (HUE,COR,CAD,SEV)', 5),
  ((select id from ccaa where codigo='ANDALUCIA'), 'ANDALUCIA (SEVILLA CIUDAD)', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'ANOIA', 2),
  ((select id from ccaa where codigo='ARAGON'), 'ARAGÓN', 2),
  ((select id from ccaa where codigo='ASTURIAS'), 'ASTURIAS', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'BAGES', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'BAIX CAMP', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'BAIX EBRE', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'BAIX EMPORDA', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'BAIX LLOBREGAT', 7),
  ((select id from ccaa where codigo='CATALUÑA'), 'BAIX PENEDES', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 01', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 02', 8),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 03', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 04', 5),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 05', 5),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 06', 4),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 07', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 08', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 09', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONA DTE. 10', 4),
  ((select id from ccaa where codigo='CATALUÑA'), 'BARCELONÈS', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'BERGUEDÀ', 1),
  ((select id from ccaa where codigo='CANTABRIA'), 'CANTABRIA', 1),
  ((select id from ccaa where codigo='CASTILLA-LA MANCHA'), 'CASTILLA-LA MANCHA', 1),
  ((select id from ccaa where codigo='CASTILLA Y LEON'), 'CASTILLA Y LEON', 5),
  ((select id from ccaa where codigo='CATALUÑA'), 'CERDANYA', 1),
  ((select id from ccaa where codigo='COMUNIDAD VALENCIANA'), 'COM. VALENCIANA (EXC.VALENCIA CIUTAT)', 6),
  ((select id from ccaa where codigo='CATALUÑA'), 'CONCA DE BARBERÀ', 1),
  ((select id from ccaa where codigo='ISLAS BALEARES'), 'EIVISSA I FORMENTERA', 2),
  ((select id from ccaa where codigo='EXTREMADURA'), 'EXTREMADURA', 1),
  ((select id from ccaa where codigo='GALICIA'), 'GALICIA', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'GARRAF', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'GIRONÈS', 4),
  ((select id from ccaa where codigo='CATALUÑA'), 'LA GARROTXA', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'LA NOGUERA', 1),
  ((select id from ccaa where codigo='LA RIOJA'), 'LA RIOJA', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'LA SELVA', 3),
  ((select id from ccaa where codigo='ISLAS CANARIAS'), 'LAS PALMAS', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'LES GARRIGUES', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'LLUÇANÈS', 1),
  ((select id from ccaa where codigo='MADRID'), 'MADRID (EXC. MADRID CIUDAD)', 5),
  ((select id from ccaa where codigo='MADRID'), 'MADRID', 6),
  ((select id from ccaa where codigo='ISLAS BALEARES'), 'MALLORCA (EXC. PALMA)', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'MARESME', 6),
  ((select id from ccaa where codigo='ISLAS BALEARES'), 'MENORCA', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'MOIANÈS', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'MONTSIA', 1),
  ((select id from ccaa where codigo='MURCIA'), 'MURCIA', 3),
  ((select id from ccaa where codigo='NAVARRA'), 'NAVARRA', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'OSONA', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'PALLARS JUSSÀ', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'PALLARS SOBIRÀ', 1),
  ((select id from ccaa where codigo='ISLAS BALEARES'), 'PALMA DE MALLORCA', 4),
  ((select id from ccaa where codigo='PAIS VASCO'), 'PAIS VASCO', 4),
  ((select id from ccaa where codigo='CATALUÑA'), 'PLA DE L''ESTANY', 2),
  ((select id from ccaa where codigo='CATALUÑA'), 'PLA D''URGELL', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'PRIORAT', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'RIBERA D''EBRE', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'RIPOLLES', 1),
  ((select id from ccaa where codigo='ISLAS CANARIAS'), 'SANTA CRUZ DE TENERIFE', 4),
  ((select id from ccaa where codigo='CATALUÑA'), 'SEGARRA', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'SEGRIA', 4),
  ((select id from ccaa where codigo='CATALUÑA'), 'SOLSONÈS', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'TARRAGONES', 3),
  ((select id from ccaa where codigo='CATALUÑA'), 'TERRA ALTA', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'URGELL', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'VALL D''ARAN', 1),
  ((select id from ccaa where codigo='CATALUÑA'), 'VALLES OCCIDENTAL', 7),
  ((select id from ccaa where codigo='CATALUÑA'), 'VALLES ORIENTAL', 4),
  ((select id from ccaa where codigo='COMUNIDAD VALENCIANA'), 'VALENCIA (CIUTAT)', 4),
  ((select id from ccaa where codigo='LA RIOJA'), 'LOGROÑO', 0)
on conflict (ccaa_id, nombre) do nothing;

insert into socios (apellidos, nombre, email, telefono, idioma, rol, activo) values
  ('CALERO VALLS', 'JOAN', 'jcalerovalls@gmail.com', null, 'ca', 'socio', true),
  ('RIGALL CARRE', 'PERE', 'rigallbordas@gmail.com', null, 'ca', 'socio', true),
  ('GONZALEZ TORRES', 'ABEL', 'abel.gonzalez.to@gmail.com', null, 'ca', 'socio', true),
  ('CABRERA CRUZ', 'ISIDRO', 'icabreracruz@gmail.com', null, 'es', 'socio', true),
  ('LOPEZ URQUIZAR', 'JOSE MANUEL', 'ascenjosemanuel2019@gmail.com', null, 'es', 'socio', true),
  ('MARTINEZ GARCIA', 'MARCELO', 'frommotril@gmail.com', '640266805', 'es', 'socio', true),
  ('RUBI CASTILLO', 'FRANCISCO', 'frubi@caixabank.com', null, 'es', 'socio', true),
  ('VANEGAS LOPEZ', 'JORGE JUAN', 'jjvanegas@caixabank.com', null, 'es', 'socio', true),
  ('CODER GALLEGO', 'ELISA ISABEL', 'eicoder@hotmail.com', null, 'es', 'socio', true),
  ('MONTIJANO LOPEZ', 'SAMUEL', 'samuelmontijano@yahoo.es', null, 'es', 'socio', true),
  ('VAZQUEZ PAVON', 'JUAN', 'vazparra@yahoo.es', null, 'es', 'socio', true),
  ('RUBIALES ALVAREZ DARDET', 'FERNANDO', 'fernandorubiales01@icloud.com', null, 'es', 'socio', true),
  ('COYA ALAEZ', 'LUIS', 'luiscoyaalaez@gmail.com', null, 'es', 'socio', true),
  ('LUQUE SAN JUAN', 'JAVIER', 'jluquesj@gmail.com', null, 'es', 'socio', true),
  ('SANFELIU SARRI', 'JOSEP', 'sanfeliu8789@gmail.com', null, 'ca', 'socio', true),
  ('BASORA SANJUAN', 'JOSEP MARIA', 'jmbasora@gmail.com', null, 'ca', 'socio', true),
  ('CASONI-VALENTI SAMARANCH', 'VERA PAOLA', 'verasonica@hotmail.com', null, 'ca', 'socio', true),
  ('CASTELLO PROVENSAL', 'CRISTINA', 'cristinacastelloprovensal@gmail.com', null, 'ca', 'socio', true),
  ('MATEU PALE', 'RAFAEL', 'rafelmateu@yahoo.es', null, 'ca', 'socio', true),
  ('LLISO LIS', 'ELISABET', 'bethlissol@gmail.com', null, 'ca', 'socio', true),
  ('MITJANS RIUS', 'JOSEP', 'mitjans.josep@gmail.com', null, 'ca', 'socio', true),
  ('RIU VIDAL', 'EDUARDO', 'lasoci.eduardriu@gmail.com', null, 'ca', 'socio', true),
  ('SIBERA ARESTE', 'JORDI', 'siberkey0@gmail.com', null, 'ca', 'socio', true),
  ('MENDOZA ROSSO', 'JOSEP', 'peprosso@hotmail.com', null, 'ca', 'socio', true),
  ('MARIEGES ASENSIO', 'FERRAN', 'fmarieges@gmail.com', null, 'ca', 'socio', true),
  ('PADRO BALCELLS', 'PERE', 'perepadrob@gmail.com', null, 'ca', 'socio', true),
  ('PAEZ MARTINEZ', 'ROSER', 'paez.roser@gmail.com', null, 'ca', 'socio', true),
  ('POYATOS JORDA', 'XAVIER', 'prexavier@yahoo.es', null, 'ca', 'socio', true),
  ('CORRECHER CASTRO', 'JOSEP', 'josepcorrecher@gmail.com', null, 'ca', 'socio', true),
  ('RUIZ CABALLERO', 'JOAN FRANCESC', 'jfruizc.lasoci@gmail.com', null, 'ca', 'socio', true),
  ('AGEA TOMAS', 'RAFAEL', 'rafelagea@gmail.com', null, 'ca', 'socio', true),
  ('PLANDOLIT ARUMI', 'JOAN', 'golfbcn@gmail.com', null, 'ca', 'socio', true),
  ('GAZULLA BADENAS', 'FERMIN', 'fergaz1997@gmail.com', null, 'ca', 'socio', true),
  ('SOLANS NAVARRO', 'ANTONI', 'antonsol25@gmail.com', null, 'ca', 'socio', true),
  ('LUMBRERAS PALOMARES', 'LUIS', 'lumbreraspalomares@gmail.com', null, 'ca', 'socio', true),
  ('PUIG LLINARES', 'FERMIN', 'fermipuig@gmail.com', null, 'ca', 'socio', true),
  ('ROIG ROCA', 'FRANCESC XAVIER', 'fxroig@gmail.com', null, 'ca', 'socio', true),
  ('MONLEON NOVELLA', 'AMADOR', 'amonleonn@gmail.com', null, 'ca', 'socio', true),
  ('RAMOS HERRERO', 'MIQUEL', 'miquelramosbcn@gmail.com', null, 'ca', 'socio', true),
  ('GOMEZ GONZALEZ', 'JOSE MANUEL', 'gomezcaixa@gmail.com', null, 'es', 'socio', true),
  ('ALONSO GONZALEZ', 'OSCAR', 'oscaralonsoglez@msn.com', null, 'es', 'socio', true),
  ('GALAN DE LA CONCEPCION', 'IRINEO', 'igalandela@gmail.com', null, 'es', 'socio', true),
  ('HORGA MANZANAL', 'GREGORIO', 'ghorga@caixabank.com', null, 'es', 'socio', true),
  ('MONTES HERNANDEZ', 'TEOFILO', 'amadeorey@me.com', null, 'es', 'socio', true),
  ('PEREZ PANIEGO', 'ROBERTO', 'roberto.perezpa@gmail.com', null, 'es', 'socio', true),
  ('MUR PLEITE', 'DANIEL', 'danimurp@gmail.com', null, 'es', 'socio', true),
  ('ALBALADEJO GISBERT', 'JOSE JOAQUIN', 'josealbala@telefonica.net', null, 'es', 'socio', true),
  ('COLLADO SAN EUSTAQUIO', 'JUAN', 'juancooperante@gmail.com', null, 'es', 'socio', true),
  ('GARCIA ESPELETA', 'RAMON', 'ramon.garcia.e@caixabank.com', null, 'es', 'socio', true),
  ('SONADELLES PLA', 'ALICIA', 'asonadelles@hotmail.es', null, 'es', 'socio', true),
  ('PALERM SERRA', 'JOAN ANTONI', 'joanpalerm@gmail.com', null, 'ca', 'socio', true),
  ('RIBAS FERRER', 'MARIA CARMEN', 'mcribas2@gmail.com', null, 'ca', 'socio', true),
  ('JEREZ FONTAO', 'LLUIS', 'jerser5@hotmail.com', null, 'ca', 'socio', true),
  ('BUSQUETS PICART', 'JOSEP', 'jbusquets04@gmail.com', null, 'ca', 'socio', true),
  ('MAYOLA PRAT', 'XAVIER', 'xevimayola@hotmail.com', null, 'ca', 'socio', true),
  ('GONZALEZ CABRERA', 'ISRAEL', 'israel.gonzalez@caixabank.com', null, 'es', 'socio', true),
  ('SANMARTIN GARCIA DE', 'JOSE CARLOS', 'cirus@telefonica.net', null, 'es', 'socio', true),
  ('TOVAL DEL SOL', 'RAFAEL', 'rtovaldel@gmail.com', null, 'es', 'socio', true),
  ('DEL CASTILLO GARCIA', 'CANDIDO', 'candidocastillo@hotmail.com', null, 'es', 'socio', true),
  ('GOMEZ LOPEZ', 'FRANCISCO', 'pinareja@telefonica.net', null, 'es', 'socio', true),
  ('TORREGO DE FRUTOS', 'FELIX', 'torrego47@yahoo.es', null, 'es', 'socio', true),
  ('MAYRATA MASCARO', 'MIQUEL', 'mmairatam@hotmail.com', null, 'ca', 'socio', true),
  ('PLANELLS TORRES', 'JOAN', 'jplanells1@yahoo.es', null, 'ca', 'socio', true),
  ('TOMAS MORLA', 'DAMIAN', 'teatrepicadis@gmail.com', null, 'ca', 'socio', true),
  ('DEL RIO HUERTAS', 'ANTONIO', 'delriohuertas@gmail.com', null, 'ca', 'socio', true),
  ('SORIANO ADZERIAS', 'ANDREU', 'andreusoriano50@gmail.com', null, 'ca', 'socio', true),
  ('SALAS HOYOS', 'PEDRO JOSE', 'pjsalas@caixabank.com', null, 'es', 'socio', true),
  ('DE IRUETA CALCEDO', 'ALVARO', 'beverlymartinezgarcia@gmail.com', null, 'es', 'socio', true),
  ('MINTEGUI ECHALECU', 'IBON', 'imintegui73@gmail.com', null, 'es', 'socio', true),
  ('BARCELO RIERA', 'FRANCESC', 'xisbari@hotmail.com', null, 'ca', 'socio', true),
  ('CRESPO MARTIN', 'MANUEL', 'papa.crespo@gmail.com', null, 'ca', 'socio', true),
  ('FERRER MOTOS', 'ENRIC', 'eferrermotos@hotmail.com', null, 'ca', 'socio', true),
  ('TUGORES SOLIVELLAS', 'JUAN', 'tugores45@gmail.com', null, 'ca', 'socio', true),
  ('COLL COMERMA', 'JOAN', 'joancollc@hotmail.com', null, 'ca', 'socio', true),
  ('TORRAS CONGOST', 'MARTIRIA', 'martiriatorras@gmail.com', null, 'ca', 'socio', true),
  ('CLUA LLOP', 'JOSEP', 'josepcluallop@hotmail.com', null, 'ca', 'socio', true),
  ('AYALA CORREA', 'CEFERINO GUILLERMO', 'cgayala@caixabank.com', null, 'es', 'socio', true),
  ('CABA BETANCORT', 'MARIA DEL MAR', 'marcaba65@gmail.com', null, 'es', 'socio', true),
  ('PEREZ PEREZ', 'SIXTO GREGORIO', 'goyoperez23@gmail.com', null, 'es', 'socio', true),
  ('CREUS VILA', 'JORDI', 'jordi.creusvila@gmail.com', null, 'ca', 'socio', true),
  ('PICANYOL TARRES', 'JOAN', 'joan.piccas@gmail.com', null, 'ca', 'socio', true),
  ('MEIX BOIRA', 'JOSE RAMON', 'josepmeix@gmail.com', null, 'ca', 'socio', true),
  ('GONZALEZ RODRIGUEZ', 'JOSE MANUEL', 'jmgr_9@hotmail.com', null, 'es', 'socio', true),
  ('HUERTA PALAU', 'JESUS MANUEL', 'j.m.a.huerta@gmail.com', null, 'es', 'socio', true),
  ('GARCIA SANTANACH', 'ROBERT', 'robertgsan@gmail.com', null, 'ca', 'socio', true),
  ('URGELES BORRAS', 'DELFI', 'delfi.urgeles@gmail.com', null, 'ca', 'socio', true),
  ('ALEGRET LLORENS', 'RICARDO', 'ricardoalegret@ricardoalegret.es', null, 'es', 'socio', true),
  ('GONZALEZ MUÑOZ', 'JOSE LUIS', 'jlmunoz@gmail.com', null, 'es', 'socio', true),
  ('ESPINOSA GARCIA', 'JUAN CARLOS', 'espyweb@gmail.com', null, 'es', 'socio', true),
  ('LOPEZ RIVERA', 'MANUEL', 'manuel.lopez.rivera.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('CORTES LOPEZ', 'CARLOS JAVIER', 'carlos.javier.cortes.lopez.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('GARCIA CABANES', 'JORGE', 'jorge.garcia.cabanes.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('FLAMARIQUE BORREGO', 'FERNANDO', 'fernando.flamarique.borrego.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 1', '', '.numero.1.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 8', '', '.numero.8.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('LEMOS SANTIAGO', 'DAVID', 'david.lemos.santiago.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('SOTO VARELA', 'JAVIER', 'javier.soto.varela.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('Numero 7', '', '.numero.7.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true),
  ('LASANTA ESTEBAN', 'RAQUEL', 'raquel.lasanta.esteban.pendiente@pendiente.lasoci.org', null, 'es', 'socio', true)
on conflict (email) do nothing;

insert into candidaturas (socio_id, territorio_id, estado, tipo_asociado, seccion, interes_rector, candidatura_presentada) values
  ((select id from socios where email='jcalerovalls@gmail.com'), (select id from territorios where nombre='ALT EMPORDA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='rigallbordas@gmail.com'), (select id from territorios where nombre='ALT EMPORDA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='abel.gonzalez.to@gmail.com'), (select id from territorios where nombre='ALT PENEDES'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='icabreracruz@gmail.com'), (select id from territorios where nombre='ANDALUCIA (ALM,GRA,JAE,MAL)'), 'ACTIVO', 'DELEGADO', 'VELA ANDALUCIA ORIENTAL', true, true),
  ((select id from socios where email='ascenjosemanuel2019@gmail.com'), (select id from territorios where nombre='ANDALUCIA (ALM,GRA,JAE,MAL)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='frommotril@gmail.com'), (select id from territorios where nombre='ANDALUCIA (ALM,GRA,JAE,MAL)'), 'ACTIVO', 'DELEGADO', 'FUTBOL GRANADA', true, true),
  ((select id from socios where email='frubi@caixabank.com'), (select id from territorios where nombre='ANDALUCIA (ALM,GRA,JAE,MAL)'), 'ACTIVO', 'DELEGADO', 'FUTBOL ALMERIA', true, true),
  ((select id from socios where email='jjvanegas@caixabank.com'), (select id from territorios where nombre='ANDALUCIA (ALM,GRA,JAE,MAL)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='eicoder@hotmail.com'), (select id from territorios where nombre='ANDALUCIA (HUE,COR,CAD,SEV)'), 'ACTIVO', 'DELEGADO', 'GASTRONOMIA HUELVA', true, true),
  ((select id from socios where email='samuelmontijano@yahoo.es'), (select id from territorios where nombre='ANDALUCIA (HUE,COR,CAD,SEV)'), 'INACTIVO', 'DELEGADO', 'ESQUI CORDOBA', false, false),
  ((select id from socios where email='vazparra@yahoo.es'), (select id from territorios where nombre='ANDALUCIA (HUE,COR,CAD,SEV)'), 'ACTIVO', 'DELEGADO', 'PESCA ANDALUCIA OCCIDENTAL', true, true),
  ((select id from socios where email='fernandorubiales01@icloud.com'), (select id from territorios where nombre='ANDALUCIA (SEVILLA CIUDAD)'), 'ACTIVO', 'DELEGADO', 'TRIATLON Y FONDISTAS SEVILLA', true, true),
  ((select id from socios where email='luiscoyaalaez@gmail.com'), (select id from territorios where nombre='ASTURIAS'), 'ACTIVO', 'DELEGADO', 'HISTORIA ASTURIAS', true, true),
  ((select id from socios where email='jluquesj@gmail.com'), (select id from territorios where nombre='ASTURIAS'), 'ACTIVO', 'DELEGADO', 'KARTING ASTURIAS', true, true),
  ((select id from socios where email='sanfeliu8789@gmail.com'), (select id from territorios where nombre='BAGES'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='jmbasora@gmail.com'), (select id from territorios where nombre='BAIX CAMP'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='verasonica@hotmail.com'), (select id from territorios where nombre='BAIX EMPORDA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='cristinacastelloprovensal@gmail.com'), (select id from territorios where nombre='BAIX EMPORDA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='rafelmateu@yahoo.es'), (select id from territorios where nombre='BAIX EMPORDA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='bethlissol@gmail.com'), (select id from territorios where nombre='BAIX LLOBREGAT'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='mitjans.josep@gmail.com'), (select id from territorios where nombre='BAIX LLOBREGAT'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='lasoci.eduardriu@gmail.com'), (select id from territorios where nombre='BAIX LLOBREGAT'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='siberkey0@gmail.com'), (select id from territorios where nombre='BAIX LLOBREGAT'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='peprosso@hotmail.com'), (select id from territorios where nombre='BAIX PENEDES'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='fmarieges@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 02'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='perepadrob@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 02'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='paez.roser@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 02'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='prexavier@yahoo.es'), (select id from territorios where nombre='BARCELONA DTE. 02'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='josepcorrecher@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 03'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='jfruizc.lasoci@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 03'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='rafelagea@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 04'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='golfbcn@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 04'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='fergaz1997@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 05'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='antonsol25@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 05'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='lumbreraspalomares@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 06'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='fermipuig@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 06'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='fxroig@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 07'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='amonleonn@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 10'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='miquelramosbcn@gmail.com'), (select id from territorios where nombre='BARCELONA DTE. 10'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='gomezcaixa@gmail.com'), (select id from territorios where nombre='CANTABRIA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='oscaralonsoglez@msn.com'), (select id from territorios where nombre='CASTILLA Y LEON'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='igalandela@gmail.com'), (select id from territorios where nombre='CASTILLA Y LEON'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='ghorga@caixabank.com'), (select id from territorios where nombre='CASTILLA Y LEON'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='amadeorey@me.com'), (select id from territorios where nombre='CASTILLA Y LEON'), 'ACTIVO', 'DELEGADO', 'GOLF CASTILLA Y LEON', true, true),
  ((select id from socios where email='roberto.perezpa@gmail.com'), (select id from territorios where nombre='CASTILLA Y LEON'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='danimurp@gmail.com'), (select id from territorios where nombre='CASTILLA-LA MANCHA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='josealbala@telefonica.net'), (select id from territorios where nombre='COM. VALENCIANA (EXC.VALENCIA CIUTAT)'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='juancooperante@gmail.com'), (select id from territorios where nombre='COM. VALENCIANA (EXC.VALENCIA CIUTAT)'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='ramon.garcia.e@caixabank.com'), (select id from territorios where nombre='COM. VALENCIANA (EXC.VALENCIA CIUTAT)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='asonadelles@hotmail.es'), (select id from territorios where nombre='COM. VALENCIANA (EXC.VALENCIA CIUTAT)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='joanpalerm@gmail.com'), (select id from territorios where nombre='EIVISSA I FORMENTERA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='mcribas2@gmail.com'), (select id from territorios where nombre='EIVISSA I FORMENTERA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='jerser5@hotmail.com'), (select id from territorios where nombre='GIRONÈS'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='jbusquets04@gmail.com'), (select id from territorios where nombre='LA GARROTXA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='xevimayola@hotmail.com'), (select id from territorios where nombre='LA GARROTXA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='israel.gonzalez@caixabank.com'), (select id from territorios where nombre='LAS PALMAS'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='cirus@telefonica.net'), (select id from territorios where nombre='LAS PALMAS'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='rtovaldel@gmail.com'), (select id from territorios where nombre='MADRID'), 'ACTIVO', 'DELEGADO', 'F.S. MADRID', true, true),
  ((select id from socios where email='candidocastillo@hotmail.com'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'ACTIVO', 'DELEGADO', 'MONTAÑA MADRID', true, true),
  ((select id from socios where email='pinareja@telefonica.net'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'ACTIVO', 'DELEGADO', 'MUSICA MODERNA MADRID', true, true),
  ((select id from socios where email='torrego47@yahoo.es'), (select id from territorios where nombre='MADRID (EXC. MADRID CIUDAD)'), 'INACTIVO', 'SOCIO', null, false, false),
  ((select id from socios where email='mmairatam@hotmail.com'), (select id from territorios where nombre='MALLORCA (EXC. PALMA)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='jplanells1@yahoo.es'), (select id from territorios where nombre='MALLORCA (EXC. PALMA)'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='teatrepicadis@gmail.com'), (select id from territorios where nombre='MALLORCA (EXC. PALMA)'), 'ACTIVO', 'DELEGADO', 'HISTORIA MALLORCA', true, true),
  ((select id from socios where email='delriohuertas@gmail.com'), (select id from territorios where nombre='MARESME'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='andreusoriano50@gmail.com'), (select id from territorios where nombre='MARESME'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='pjsalas@caixabank.com'), (select id from territorios where nombre='MURCIA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='beverlymartinezgarcia@gmail.com'), (select id from territorios where nombre='PAIS VASCO'), 'ACTIVO', 'DELEGADO', 'PADEL PAIS VASCO', true, true),
  ((select id from socios where email='imintegui73@gmail.com'), (select id from territorios where nombre='PAIS VASCO'), 'ACTIVO', 'DELEGADO', 'BALONCESTO BIZKAIA ARABA', true, true),
  ((select id from socios where email='xisbari@hotmail.com'), (select id from territorios where nombre='PALMA DE MALLORCA'), 'ACTIVO', 'DELEGADO', 'JOCS DE TAULA MALLORCA', true, true),
  ((select id from socios where email='papa.crespo@gmail.com'), (select id from territorios where nombre='PALMA DE MALLORCA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='eferrermotos@hotmail.com'), (select id from territorios where nombre='PALMA DE MALLORCA'), 'ACTIVO', 'DELEGADO', 'GOLF MALLORCA', true, true),
  ((select id from socios where email='tugores45@gmail.com'), (select id from territorios where nombre='PALMA DE MALLORCA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='joancollc@hotmail.com'), (select id from territorios where nombre='PLA DE L''ESTANY'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='martiriatorras@gmail.com'), (select id from territorios where nombre='PLA DE L''ESTANY'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='josepcluallop@hotmail.com'), (select id from territorios where nombre='PRIORAT'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='cgayala@caixabank.com'), (select id from territorios where nombre='SANTA CRUZ DE TENERIFE'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='marcaba65@gmail.com'), (select id from territorios where nombre='SANTA CRUZ DE TENERIFE'), 'ACTIVO', 'DELEGADO', 'GASTRONOMIA TENERIFE', true, true),
  ((select id from socios where email='goyoperez23@gmail.com'), (select id from territorios where nombre='SANTA CRUZ DE TENERIFE'), 'ACTIVO', 'DELEGADO', 'F.S. TENERIFE', true, true),
  ((select id from socios where email='jordi.creusvila@gmail.com'), (select id from territorios where nombre='SEGARRA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='joan.piccas@gmail.com'), (select id from territorios where nombre='SEGRIA'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='josepmeix@gmail.com'), (select id from territorios where nombre='TARRAGONES'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='jmgr_9@hotmail.com'), (select id from territorios where nombre='VALENCIA (CIUTAT)'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='j.m.a.huerta@gmail.com'), (select id from territorios where nombre='VALENCIA (CIUTAT)'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='robertgsan@gmail.com'), (select id from territorios where nombre='VALL D''ARAN'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='delfi.urgeles@gmail.com'), (select id from territorios where nombre='VALLES OCCIDENTAL'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='ricardoalegret@ricardoalegret.es'), (select id from territorios where nombre='VALLES ORIENTAL'), 'ACTIVO', 'DELEGADO', null, true, true),
  ((select id from socios where email='jlmunoz@gmail.com'), (select id from territorios where nombre='ANDALUCIA (HUE,COR,CAD,SEV)'), 'ACTIVO', 'DELEGADO', 'KARTING SEVILLA', true, true),
  ((select id from socios where email='espyweb@gmail.com'), (select id from territorios where nombre='ANDALUCIA (HUE,COR,CAD,SEV)'), 'ACTIVO', 'DELEGADO', 'MULTIJUEGOS SEVILLA', true, true),
  ((select id from socios where email='manuel.lopez.rivera.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='ANDALUCIA (SEVILLA CIUDAD)'), 'ACTIVO', 'DELEGADO', 'MULTIAVENTURA SEVILLA', true, true),
  ((select id from socios where email='carlos.javier.cortes.lopez.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='ANDALUCIA (SEVILLA CIUDAD)'), 'ACTIVO', 'DELEGADO', 'VELA Y MOTONAUTICA HUELVA', true, true),
  ((select id from socios where email='jorge.garcia.cabanes.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='ARAGÓN'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='fernando.flamarique.borrego.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='ARAGÓN'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='.numero.1.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='BAIX EBRE'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='.numero.8.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='BARCELONA DTE. 05'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='david.lemos.santiago.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='EXTREMADURA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='javier.soto.varela.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='GALICIA'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='.numero.7.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='GIRONÈS'), 'ACTIVO', 'SOCIO', null, true, true),
  ((select id from socios where email='raquel.lasanta.esteban.pendiente@pendiente.lasoci.org'), (select id from territorios where nombre='LOGROÑO'), 'ACTIVO', 'DELEGADO', 'ACTIVIDAD FISICA LOGROÑO', true, true);

-- Snapshot inicial (14/6/2026)
insert into snapshots (fecha, etiqueta, activos, pendientes, inactivos, candidaturas_total, afines) values
  ('2026-06-14', 'Situación inicial', 87, 113, 0, 87, 31);

insert into snapshots_ccaa (snapshot_id, ccaa_id, activos, pendientes) values
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='CATALUÑA'), 42, 83),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='ANDALUCIA'), 9, 4),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='ASTURIAS'), 2, 0),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='CANTABRIA'), 1, 0),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='CASTILLA Y LEON'), 5, 0),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='CASTILLA-LA MANCHA'), 1, 0),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='COMUNIDAD VALENCIANA'), 6, 4),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='ISLAS BALEARES'), 9, 2),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='ISLAS CANARIAS'), 5, 1),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='MADRID'), 4, 7),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='MURCIA'), 1, 2),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='PAIS VASCO'), 2, 2),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='ARAGON'), 0, 2),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='EXTREMADURA'), 0, 1),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='GALICIA'), 0, 1),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='LA RIOJA'), 0, 2),
  ((select id from snapshots where fecha='2026-06-14'), (select id from ccaa where codigo='NAVARRA'), 0, 2);